# Generated by Django 3.0.8 on 2020-07-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bus_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=100)),
                ('origin_place', models.CharField(max_length=100)),
                ('destination_place', models.CharField(max_length=100)),
                ('bus_type', models.CharField(max_length=100)),
                ('journey_date', models.DateField()),
                ('depature_time', models.CharField(max_length=100)),
            ],
        ),
    ]
