# Generated by Django 3.0.8 on 2020-07-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_bus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bus_details',
            new_name='details',
        ),
    ]
