# Generated by Django 3.0.8 on 2020-07-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=100)),
                ('driver_first_name', models.CharField(max_length=100)),
                ('driver_last_name', models.CharField(max_length=100)),
                ('driver_username', models.CharField(max_length=100)),
                ('driver_password', models.CharField(max_length=100)),
                ('driver_email', models.CharField(max_length=100)),
            ],
        ),
    ]
